global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: cupula-celestial
    env: poc

scrape_configs:
  - job_name: hmi-gateway
    static_configs:
      - targets: ["hmi-gateway:8080"]
        labels:
          service: hmi-gateway

  - job_name: audit-log
    static_configs:
      - targets: ["audit-log:9300"]
        labels:
          service: audit-log

  - job_name: sensor-ingest
    static_configs:
      - targets: ["sensor-ingest:9000"]
        labels:
          service: sensor-ingest

  - job_name: track-fusion
    static_configs:
      - targets: ["track-fusion:9100"]
        labels:
          service: track-fusion

  - job_name: decision-engine
    static_configs:
      - targets: ["decision-engine:8002"]
        labels:
          service: decision-engine

  - job_name: threat-classifier
    static_configs:
      - targets: ["threat-classifier:8001"]
        labels:
          service: threat-classifier

  - job_name: policy-engine
    static_configs:
      - targets: ["policy-engine:8181"]
        labels:
          service: opa
